services:
  db:
    image: mariadb:11
    container_name: gestor-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: gestor_db
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    build: .
    container_name: gestor-backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "sleep 5 && npm start"

volumes:
  db_data:
